### ISSUE TITLE
Armar documento de Metadata en base al template del drive

### ISSUE THREAD

**Issue by chadad** [gobabiertoAR/audiencias#25]
Si es relevante agregar campos nuevos, agregarlos al doc resaltándolos.

**Comment by meliascosta** [comment]
Me falta info para completar toda la metadata.

**Comment by abenassi** [comment]
Fijate en el documento de requerimientos que está en el Drive de la DN
Datos si hay algunas indicaciones que te puedan ayudar con algunos campos
de la metadata (tiene contexto sobre el tema Audiencias).

2016-02-12 18:09 GMT-03:00 Martin Elias Costa <notifications@github.com>:
